name: knot-resolver-gael
version: "v5.7.4-20241117"
base: core24
summary: Knot Resolver
description: |
  Knot Resolver is a caching full resolver implementation written in C and LuaJIT, both a resolver library and a daemon. The core architecture is tiny and efficient, and provides a foundation and a state-machine like API for extensions. There are three modules built-in - iterator, validator, cache, and a few more are loaded by default. Most of the rich features are written in Lua(JIT) and C. Batteries are included, but optional.

  The LuaJIT modules, support DNS privacy and DNSSEC, and persistent cache with low memory footprint make it a great personal DNS resolver or a research tool to tap into DNS data. TL;DR it's the OpenResty of DNS.

  Strong filtering rules, and auto-configuration with etcd make it a great large-scale resolver solution.

  The server adopts a different scaling strategy than the rest of the DNS recursors - no threading, shared-nothing architecture (except MVCC cache that may be shared) that allows you to pin instances on available CPU cores and grow by self-replication. You can start and stop additional nodes depending on the contention without downtime.
  It also has strong support for DNS over TCP, notably TCP Fast-Open, query pipelining and deduplication, and response reordering.

grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

license: "GPL-3.0"

# Add the official package repository
package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 9C71D59CD4CE8BD2966A7A3EAB6A303124019B64
    url: https://pkg.labs.nic.cz/knot-resolver
    priority: always

layout:
  /usr/lib/knot-resolver:               # Needed to workaround absolute paths in Knot Resolver
    bind: $SNAP/usr/lib/knot-resolver
  /usr/share/dns:                       # Needed to workaround absolute paths in Knot Resolver
    bind: $SNAP/usr/share/dns
  /var/cache:                           # Needed to enable write access to the cache
    bind: $SNAP_DATA/var/cache
  /etc/wgetrc:                          # Needed by wget
    bind-file: $SNAP/etc/wgetrc

apps:
  kresd:
    command: launcher/kresd.sh
    daemon: simple
    install-mode: disable
    environment:
      LUA_PATH: $SNAP/usr/lib/knot-resolver/?.lua;$SNAP/usr/lib/knot-resolver/?/init.lua;$SNAP/./?.lua;$SNAP/usr/share/luajit-2.1.0-beta3/?.lua;$SNAP/usr/share/lua/5.1/?.lua;$SNAP/usr/share/lua/5.1/?/init.lua
      LUA_CPATH: $SNAP/usr/lib/knot-resolver/?.so;$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/?.so;$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lua/5.1/?.so
    plugs:
      - network
      - network-bind
      - home

  deny-policy:
    command: policies/deny_policy.sh    # Rebuild the deny list every 4 hrs
    daemon: simple
    install-mode: disable
    timer: 00:00-24:00/6
    plugs:
      - network

#  kres-cache-gc:
#    command: usr/sbin/kres-cache-gc
#    daemon: simple

parts:
  launcher:
    plugin: dump
    source: snap/local/launcher
    organize:
      'kresd.sh' : launcher/
    stage:
      - launcher/kresd.sh

  policies:
    plugin: dump
    source: snap/local/policies
    stage-packages:
      - wget
      - lua-cqueues
    organize:
      'deny_policy.sh' : policies/
    stage:
      - policies/deny_policy.sh
      - etc/*
      - usr/*
    override-prime:
      craftctl default

      rm -rf $CRAFT_PRIME/usr/share/doc
      rm -rf $CRAFT_PRIME/usr/share/info
      rm -rf $CRAFT_PRIME/usr/share/man

  kresd:
    plugin: nil
    stage-packages:
      - knot-resolver
      - knot-resolver-module-dnstap

    override-prime: |
      craftctl default

      rm -rf $CRAFT_PRIME/etc/knot-resolver
      rm -rf $CRAFT_PRIME/lib
      rm -rf $CRAFT_PRIME/usr/lib/tmpfiles.d
      rm -rf $CRAFT_PRIME/usr/share/doc
      rm -rf $CRAFT_PRIME/usr/share/man
